kda_blog_homepage:
    pattern:  /
    defaults: { _controller: KDABlogBundle:Page:index }
    requirements:
        _method:  GET
kda_blog_show:
    pattern:  /{id}
    defaults: { _controller: KDABlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+
kda_blog_new:
    pattern:  /create
    defaults: { _controller: KDABlogBundle:Blog:create }
    requirements:
        _method:  GET
kda_blog_create:
    pattern:  /create
    defaults: { _controller: KDABlogBundle:Blog:create }
    requirements:
        _method:  POST